#!/bin/bash 

name=$(basename $0)
echo file name is $name
if [ $name = "addem" ]
then
    total=$[ $1 + $2 ]
elif [ $name = "multem" ]
then
    total=$[ $1 * $2 ]
fi
echo 
echo The calculated value is $total
